### ISSUE TITLE
[Request] Make Mouse4 bindable again

### ISSUE THREAD

**Issue by cammy8580** [sneakyevil/SD-RenderTweaker#12]
In SDDE, you cannot bind MOUSE4 at all. Instead, it will immediately make itself bind to MOUSE5, despite there not only being code, and UI elements for MOUSE4. This was not the case in the original SD from 2012, which allowed you to bind it with zero problems.

I know this isn't necessarily a visual thing, but even then, it would be great if it were to finally be fixed.

**Comment by sneakyevil** [comment]
Make fix as separated plugin which you can download here: https://github.com/SDmodding/Mouse4Fix/releases/tag/Plugin
