### ISSUE TITLE
Game crashing and joystick don't work

### ISSUE THREAD

**Issue by luis0henrique** [sneakyevil/SD-RenderTweaker#15]
So, I only want a mod to change the subtitles sizes, is possible to do _just that_ with this mod?

Also, everytime I make a change in the mod menu, the joystick stops working or the game freezes and I can't do nothing but restart the game, and the changes I've made doesn't save.

**Comment by sneakyevil** [comment]
No idea why you both referring to this as "mod menu" when it's Render Tweaker, anyway I have no idea what kind of steps you even did to even introduce such issue. The gui is usable only with keyboard/mouse and not intended to be used with gamepad at all. Having xbox one controller plugged in and opening/closing the gui doesn't introduce any issue that would cause the controller to stop working.

**Comment by gbdrbob** [comment]
Apologies for the wrong terminology. I meant “mod menu” as a generic term for the render tweaker settings window. 

I think the issue may be due to an interaction with Steam Input, which I believe hooks into the game exe. I’ll test on my windows desktop to see if the issue happens there as well.

**Comment by sneakyevil** [comment]
That still shouldn't be the case, you both are doing something obviously wrong. I just went ahead and copied the files as the installation has it written and booted it up on steam deck and setup custom bind for the shoulder R5 button to F10 so I can bring up the gui and even after closing it I can still use the controller without any issues. Here is video with proof:


https://github.com/user-attachments/assets/a54acd26-00a8-40ea-aa37-fce3e378dfd3

**Comment by gbdrbob** [comment]
Thank you for your reply/help. I’ve narrowed down the issue. 

The gamepad only freezes if I close Render Tweaker using the mouse pointer to click the X in the top right corner of the interface. If I press F10 to close the window then gamepad controls remain active. 

After closing render tweaker with the mouse pointer, I can reactivate the gamepad by opening and closing render tweaker with F10.

**Comment by gbdrbob** [comment]
Thank you for your reply/help. I’ve narrowed down the issue.

The gamepad only freezes if I close the Render Tweaker UI using the mouse pointer to click the X in the top right corner of the interface. If I press F10 to close the window then gamepad controls remain active.

After closing render tweaker with the mouse pointer, I can reactivate the gamepad by opening and closing render tweaker with F10.

It does seem obvious now but after switching to the mousepad to interact with the Render Tweaker UI, switching back to use a gamepad button to close the UI didn’t occur to me before.

I’m not sure I’d agree that it counts as me doing something _obviously wrong_, but the bug has moved from annoying to a minor inconvenience for me now I know not to close the UI with the mouse pointer.

**Comment by sneakyevil** [comment]
Thanks for clarification of the issue. Fixed in `v1.8.3`, closing this as completed.
