### ISSUE TITLE
Red Highlighted Explosives Still Appear With The Option Disabled When Aiming With A Gun

### ISSUE THREAD

**Issue by vitobigmansex** [sneakyevil/SD-RenderTweaker#18]
Hello goat, i plan to resub soon but just wanted to let you know that with the option that removes red highlighted objects, while aiming with a firearm you can still see explosive objects like the red barrels, blue canisters by food stalls and the explosive thing in the Ponytail fight in Big Smile Lee, but i assume they'd all be recognized the same to you anyway. 

but yeah explosive objects are still highlighted with a gun equipped. 

besides that i dont think i can think of anything else to to add to this you've helped me a lot with the things i requested before.

plan to resub soon, looking forward to your progress on SD Mod Menu and the Scarface stuff

**Comment by sneakyevil** [comment]
This is not really issue, but rather option to add. The explosives are different type of highlight object. I will push update soon with the option to disable it or change color of it.

**Comment by sneakyevil** [comment]
Added in `v1.8.2`.
