### ISSUE TITLE
Does not adjust to 2nd monitor's FPS.

### ISSUE THREAD

**Issue by staticulator** [sneakyevil/SD-RenderTweaker#19]
Hey there! 
Thank you for your mod. It removes the bar from the other display, but it doesn't adapt to the other display's frame rate. So for e.g. my one monitor is 144 hz, and other 240 hz, but it remains restricted to 60fps. If I run the game on my 144hz monitor, it gives me the full 144hz, I have tried going into the settings and checking everything, but nothing works.

**Comment by sneakyevil** [comment]
This is kind of unrelated to the render tweaker and it's how normal games behaves where it fetch highest refresh rate from primary monitor and not secondary. You either set your secondary as primary monitor or try somehow launching the game at the second monitor instead moving the window there.
