### ISSUE TITLE
My game is lagging alot after I downloaded the mod.

### ISSUE THREAD

**Issue by mirrorsedgeios** [sneakyevil/SD-RenderTweaker#3]
When I donloaded the mod and booted up the game, the game was lagging alot more than it used to. I deleted the mod stuff like the plugin but it still lags nonetheless. Any help pls?

**Comment by sneakyevil** [comment]
This has nothing to do with the plugin. If you got still same issues even after removing it then it's your pc issue and not plugin itself. If you didn't have issues before installing it then reinstall game and make sure to backup the save files.

**Comment by mirrorsedgeios** [comment]
Thanks it worked!!!
