### ISSUE TITLE
option to remove health around enemies, yknow the circles

### ISSUE THREAD

**Issue by vitobigmansex** [sneakyevil/SD-RenderTweaker#5]
as it says. unsure if its possible, but it'd fit well with the attack highlights setting to complete my 'No Hud' preset. thanks g i appreciate your work

**Comment by sneakyevil** [comment]
Do you mean those 4 rounded bars under character?
![image](https://github.com/sneakyevil/SD-RenderTweaker/assets/29150970/8383fab3-f85b-4455-8b1f-d1d5936b3155)

**Comment by sneakyevil** [comment]
If that's the thing you wanted, I added it in `v1.6.1`.

**Comment by vitobigmansex** [comment]
yessir thats what i wanted, thanks a lot it works

**Comment by sneakyevil** [comment]
Good to hear that, closing this as completed. If you have any other request just open new issue.
