### ISSUE TITLE
Disable environment objects highlighting while grappling and disable certain attack counter prompts/interaction prompts

### ISSUE THREAD

**Issue by vitobigmansex** [sneakyevil/SD-RenderTweaker#6]
hello, probably the last time ill do one of these because i think ive nearly got all i could want.

- Disable environment objects highlighting while grappling.

When someone is grappled all objects that are used for contextual kills are highlighted, vending machines etc. 

![image_2024-01-26_183918363](https://github.com/sneakyevil/SD-RenderTweaker/assets/157213695/c48d5c56-ea42-44ba-bc62-1624213679b0)

![image_2024-01-26_184042605](https://github.com/sneakyevil/SD-RenderTweaker/assets/157213695/27a4bfc1-e9ee-4f22-80c5-513d77936f7e)

- Disable certain attack counter prompts.

This one might be more tricky (?). Basically when a grappler grabs you so you gotta spam to break out/grappler grab attacks you/striker grabs you theres a button prompt that comes up to get out of it. just want those disabled, but idk if it might be difficult.

![image_2024-01-26_175646522](https://github.com/sneakyevil/SD-RenderTweaker/assets/157213695/cf2356df-87ce-4fc2-b57e-e63b8c3c354b)

![image_2024-01-26_175745923](https://github.com/sneakyevil/SD-RenderTweaker/assets/157213695/9703931c-1162-450f-a3d1-f7c00c85bc19)

![image_2024-01-26_182203246](https://github.com/sneakyevil/SD-RenderTweaker/assets/157213695/b62c159e-b47f-4dbf-b1a8-c7d0e9eed3b5)

![image_2024-01-26_183310991](https://github.com/sneakyevil/SD-RenderTweaker/assets/157213695/676d6997-9434-47d5-a299-af6a85ec1b88)

This BSL striker did a grapple attack on me however i didnt time the screenshot right and it took like 10 minutes for him to do it but yeah these guys have a grapple attack with an icon

- Disable interaction prompts.

Stuff like picking up weapons, grappling a downed enemy, vaulting, climbing, sleeping theres a little icon thing that comes up. Not sure if this is too much hassle or if it all works the same way to disable them, *but if its too much you can just disable the climbing and picking up downed enemies icons*.

![image_2024-01-26_175542019](https://github.com/sneakyevil/SD-RenderTweaker/assets/157213695/a13b8d3b-f788-485f-a963-573ef0ce8e82)

![image_2024-01-26_183504147](https://github.com/sneakyevil/SD-RenderTweaker/assets/157213695/1e8c09aa-d97e-4af9-888c-9ba0875deb58)

![image_2024-01-26_183525510](https://github.com/sneakyevil/SD-RenderTweaker/assets/157213695/ef4f67b8-4331-4d03-98d5-adc5f8e3f748)

![image_2024-01-26_183545766](https://github.com/sneakyevil/SD-RenderTweaker/assets/157213695/9a4df78c-59ab-4659-8252-6c5b3c31cdc8)

![image_2024-01-26_183734926](https://github.com/sneakyevil/SD-RenderTweaker/assets/157213695/eb987936-7269-4c04-b7c7-d76cf0a7acf5)

Again, idk if you can even do this so you if you cant its perfectly chill and im already happy with what you did last time. thanks g

(this is my 2nd time ever posting anything on this platform so idk if the screenshots are going to clog up half the screen or will be placed in their respective paragraphs but i hope you can still see what i mean even if they arent)

**Comment by sneakyevil** [comment]
Added options to disable all of them in `v1.7.0`. Let me know if I missed something.
