### ISSUE TITLE
Request to add "Disable Crosshair" option

### ISSUE THREAD

**Issue by ForeChin99** [sneakyevil/SD-RenderTweaker#7]
Thank you a lot for your work, Sleeping Dogs has a "Disable Hud" option in the menu, but it disables even the phone you pull up, which makes the game inconvenient to play without HUD, your mod essentially fixes that, thank you for making it possible to enjoy this game again in a new way, but is it possible to add the option to disable crosshair as well?

**Comment by ForeChin99** [comment]
I was also wondering if it's possible to keep the navigation feature that happens when pressing "M" on the keyboard or "L3" on a gamepad (switching between objectives) _while_ keeping the minimap hidden? Because currently disabling the minimap seems to disable this feature as well

**Comment by sneakyevil** [comment]
Fixed the bug and added option to toggle the objective indicator and also option to toggle crosshair in `v1.8.0`.
